### ISSUE TITLE
Contract library for Bentley Ottman algorithm

### ISSUE THREAD

**Issue by Jonybang** [galtspace/galtproject-contracts#171]
Sources:
- [Bentley Ottman javascript implemetation](https://github.com/ggolikov/bentley-ottman/)
- [Bentley Ottman python implemetation](https://github.com/splichte/lsi)
- [Bentley Ottman wiki](https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC_%D0%91%D0%B5%D0%BD%D1%82%D0%BB%D0%B8_%E2%80%94_%D0%9E%D1%82%D1%82%D0%BC%D0%B0%D0%BD%D0%BD%D0%B0)
- [Sweep-line algorithms, an video example](https://www.youtube.com/watch?v=phrSBwaBs7o)
- [Red-black tree implementation in Solidity for Bentley Ottman implemetation](https://github.com/AtlantPlatform/rbt-solidity)
- [Weiler-Atherton video tutorial](https://www.youtube.com/watch?v=LCMyWFxeuro)
- [Weiler-Atherton rust implemetation](https://github.com/lempiy/Weiler-Atherton-Clipping)
- [Explain Weiler-Atherton polygon clipping algorithm on ques10](http://www.ques10.com/p/22055/explain-weiler-atherton-polygon-clipping-algorit-2/)
- [Student's research about Weiler-Atherton](https://www.cg.tuwien.ac.at/research/publications/2014/WINKLER-2013-AMO/WINKLER-2013-AMO-Thesis.pdf)
- [Princeton University Algorithms course](https://www.coursera.org/learn/algorithms-part1/home/welcome)
- http://www.ams.sunysb.edu/~jsbm/courses/345/13/bentley-ottmann.pdf
- https://bl.ocks.org/1wheel/464141fe9b940153e636

**Comment by chebykin** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Estimate gas costs for the Bentley Ottman algorithm #178](https://github.com/galtspace/galtproject-contracts/issues/178) [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/bKis/issues/7222646) | Sprint #13 | Jonybang | Untriaged | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Write tests for the Bentley Ottman algorithm #177](https://github.com/galtspace/galtproject-contracts/issues/177) [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/bKis/issues/7222645) | Sprint #13 | Jonybang | Untriaged | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Transfer the Bentley Ottman algorithm to Solidity using the binary tree search library #176](https://github.com/galtspace/galtproject-contracts/issues/176) [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/bKis/issues/7222644) | Sprint #13 | Jonybang | Untriaged | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-closed.svg) [Connect and, if necessary, modify the third-party Solidity library of binary search in the tree for using in Wyler-Utterton algorithm #175](https://github.com/galtspace/galtproject-contracts/issues/175) [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/bKis/issues/7222639) | Sprint #13 | Jonybang | Done | Closed
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-closed.svg) [Estimate gas costs for utils functions of checking the intersection of vectors and polygons #174](https://github.com/galtspace/galtproject-contracts/issues/174) [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/bKis/issues/7222633) | Sprint #13 | Jonybang | Done | Closed
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-closed.svg) [Write tests for utils functions of checking the intersection of vectors and polygons #173](https://github.com/galtspace/galtproject-contracts/issues/173) [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/bKis/issues/7222630) | Sprint #13 | Jonybang | Done | Closed
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-closed.svg) [Transfer the utils functions of checking the intersection of vectors and polygons to Solidity #172](https://github.com/galtspace/galtproject-contracts/issues/172) [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/bKis/issues/7222623) | Sprint #13 | Jonybang | Done | Closed


###### do-not-edit-end-codetree-epic-issues
